# This workflow will release project to PyPI
name: CloudFormation CLI Hooks Extension Release

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install --upgrade wheel twine
    - name: Package project
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish distribution 📦 to PyPI (If triggered from release)
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}